kbase/ui-common

src/widgets/jgi/kbaseJgiDataImportView.js
Make one render method that takes a set of parameters that tell it how
to render for a specific type.
=> Merge & parameterize the render methods

src/widgets/jgi/kbaseJgiDataImportView.js
Basic functionality complete, needs:
1) to deal with Narrative workspaces & names vs. all workspaces (how deal with non-unique narrative names?)
2) link to app
3) maybe some tarting up?
=> Add copying objects to jgi page

src/widgets/jgi/kbaseJgiDataImportView.js
Currently only works for reads. Annotations removed for now. Will add
assemblies later.
=> Add link to narrative manager to launch app with data

src/widgets/narrativemanager/NarrativeManager.js
the narrative manager now checks all workspaces with narrative metadata
in order of date until it finds a retrievable narrative
=> [NarrMgr] fix bug when narrative manually deleted

src/widgets/genomes/kbaseGeneDomains.js
UI improvement for domains card, so entire table is visible by default
=> Updated kbaseGeneDomains card to toggle on click between short and ridiculously long domain descriptions

src/widgets/narrativemanager/NarrativeManager.js
Fairly large refactor but should make code easier to understand as it's no longer a huge heavily indented block. Major functionality change was to use the alter_metadata callbacks to ensure it either completes or errors out before redirecting the page.
=> [NarrMgr] refactor createTempNarrative to report alter meta failures

functional-site/js/app.js, functional-site/js/search.js, functional-site/views/dashboard/dashboard.html, src/widgets/dashboard/AppsWidget/templates/authorized.html, src/widgets/dashboard/DataWidget/templates/authorized.html, src/widgets/dataview/DataviewWidget.js, src/widgets/dataview/OverviewWidget.js, src/widgets/dataview/OverviewWidget/templates/error.html, src/widgets/dataview/OverviewWidget/templates/main.html
update dashboard to remove data panel
update dataview to handle missing object version
logout does not trap the current path as the nextPath
search logout goes to login page, not returning to search
=> Narrative dev

functional-site/index.html, src/widgets/dataview/kbaseDataViewGenericViz.js, src/widgets/from_narrative/kbaseAnnotationSetTable.js, src/widgets/from_narrative/kbaseAssemblyView.js, src/widgets/from_narrative/kbaseDomainAnnotation.js
ported over viewers for AssemblyReport, DomainAnnotation, & MetagenomeAnnotation; configured PanGenome viewer correctly.
finishes https://atlassian.kbase.us/browse/KBASE-1512
=> Added missing viewers for landing pages

src/widgets/narrativemanager/NarrativeManager.js
Left the old text commented out and updated with Nomi's new text and links.
=> Updated intro text in NarrativeManager

src/clients/kbaseClientMethods.js, src/widgets/dashboard/DashboardWidget.js, src/widgets/dashboard/NarrativesWidget/templates/slider.html, src/widgets/dashboard/NarrativesWidget/templates/table.html, src/widgets/dashboard/SharedNarrativesWidget/templates/slider.html, src/widgets/dashboard/SharedNarrativesWidget/templates/table.html, src/widgets/dashboard/style.css
Update dashboard display of metadata - counts of app, method, code & markdown cell, objects.
Rearranged slides to better match spec.
=> Dashboard update

src/widgets/communities/kbaseAbundanceDataPcoa.js, src/widgets/communities/kbaseCollectionView.js
Critical fix as referenced here: https://atlassian.kbase.us/browse/KBASE-1570
=> Updated communities landing pages.

src/kbaseSessionSync.js
Fix login bug in handling of corrupt cookie.
=> Improved handling of corrupt cookie

functional-site/js/search.js, functional-site/views/search/search.html
Should let Matt take a look at this before merging
=> [Search] use Narrative name vs WS name

src/widgets/communities/kbaseAbundanceDataBoxplot.js, src/widgets/communities/kbaseAbundanceDataHeatmap.js, src/widgets/communities/kbaseAbundanceDataPcoa.js, src/widgets/communities/kbaseAbundanceDataTable.js, src/widgets/communities/kbaseAbundanceDataView.js, src/widgets/communities/kbaseCollectionView.js, src/widgets/communities/kbaseMetagenomeView.js, src/widgets/communities/kbaseRankAbundancePlot.js, src/widgets/fbas/kbaseFormulationForm.js, src/widgets/from_narrative/kbaseAnnotationSetTable.js, src/widgets/from_narrative/kbaseDomainAnnotation.js, src/widgets/genomes/kbaseGeneExprLinePlot.js, src/widgets/genomes/kbaseGeneStructureMatches.js, src/widgets/genomes/kbaseGenomeLineage.js, src/widgets/genomes/kbaseGenomeOverview.js, src/widgets/genomes/kbaseLitWidget.js, src/widgets/mak/kbaseMAKResultCard.js, src/widgets/protcmp/kbaseGenomeComparison.js, src/widgets/trees/kbaseMSA.js, src/widgets/trees/kbaseTree.js
First, I found that the landing page for the Communities.Collection has wrong loading image url, but then it turned that the same problem might be for other landing pages... 
More about it here: https://atlassian.kbase.us/browse/KBASE-1604
=> Updated loading image URL to assets/img/ajax-loader.gif

functional-site/index.html, src/widgets/assembly/kbaseAssemblyInput.js, src/widgets/assembly/kbaseFilePairedEndLibrary.js, src/widgets/assembly/kbasePairedEndLibrary.js, src/widgets/assembly/kbaseReferenceAssembly.js, src/widgets/assembly/kbaseSingleEndLibrary.js, src/widgets/assembly/kbaseSingleObjectBasicWidget.js, src/widgets/dataview/kbaseDataViewGenericViz.js
I created basic landing pages for the following datatypes:
KBaseAssembly.AssemblyInput
KBaseAssembly.PairedEndLibrary
KBaseAssembly.ReferenceAssembly
KBaseAssembly.SingleEndLibrary
KBaseFile.PairedEndLibrary
=> Landing pages for assembly related datatypes

src/widgets/dashboard/DashboardWidget.js, src/widgets/dashboard/MetricsWidget.js, src/widgets/dashboard/MetricsWidget/templates/authorized.html, userMetrics/narrative_histogram.json, userMetrics/narrative_shared_histogram.json, userMetrics/narrative_sharing_histogram.json
simplify histograms while retaining enough useful information
=> Add date to bottom of dashboard histograms

src/widgets/genomes/kbaseGenomeGeneTable.js
First and last page buttons are there.
=> NAR-333: Gene table size is now selectable in Genome LP.

functional-site/config.json, functional-site/index.html, src/widgets/LoginWidget/templates/loggedout.html, src/widgets/narrativemanager/NarrativeManager.js
This one is identical to the deploy hotfix -- no conflicts to resolve.
=> Hotfix 1884 fix staging links

src/widgets/dashboard/CollaboratorsWidget/templates/authorized.html, src/widgets/dashboard/ProfileWidget/templates/stub_profile.html, src/widgets/social/UserProfile/templates/no_profile.html, src/widgets/social/UserProfile/templates/stub_profile.html
See https://atlassian.kbase.us/browse/KBASE-2304
=> Improve text that appears on empty dashboard

src/kbwidget.js
It's not jsdoc, but I figure if this widget's obsolete and going to be replaced anyway, it's better to just get lots of usage docs in there and worry about the re-formatting if it gets a reprieve.
=> added a big block of text documentation at the top.

.gitignore, functional-site/index.html, src/widgets/modeling/KBModeling.js, src/widgets/modeling/KBObjects.js, src/widgets/modeling/KBaseBiochem.Media.js, src/widgets/modeling/KBaseFBA.FBA.js, src/widgets/modeling/KBaseFBA.FBAComparison.js, src/widgets/modeling/KBaseFBA.FBAModel.js, src/widgets/modeling/KBaseFBA.FBAModelSet.js, src/widgets/modeling/KBasePhenotypes.PhenotypeSet.js, src/widgets/modeling/KBasePhenotypes.PhenotypeSimulationSet.js, src/widgets/modeling/KBaseSearch.GenomeSet.js, src/widgets/modeling/kbasePathways.js, src/widgets/modeling/kbaseTabTable.js, src/widgets/modeling/modelSeedVizConfig.js, src/widgets/modeling/msPathway.js
Adding model and fba maps; This includes renaming KBObjects -> KBModeling and moving "kbapi" to KBModeling.
=> Modeling sprint

loading.html
Fix for https://atlassian.kbase.us/browse/KBASE-1654
=> Remove "(prototype)" from page title

src/widgets/dashboard/PublicNarrativesWidget.js, src/widgets/dashboard/PublicNarrativesWidget/templates/slider.html
Primarily to ensure that the public narrative slider is indeed public narratives. While in there also fixed a bug with the public narrative slider resetting a search up on the 1/sec refresh. The changes look noisier than they should be because of a retabbing of the file.
=> Kbase 1872 hotfix - public narrative slider

src/widgets/social/UserProfile/templates/view.html, src/widgets/social/kbaseUserProfileWidget.js
=> Remove help menu option from user profile widget, and the associated
